### ISSUE TITLE
Fix weird bug from w1thermsensor code that crashes main.py sometimes

### ISSUE THREAD

**Issue by billyen33** [ESW-NU/AutoAquaponics#61]
At one point main.py crashed after running for about a day. The terminal gave the error message below:

`Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 48, in start_data_logging
    DataLogger()
  File "/home/pi/AutoAquaponics/DataLogger.py", line 25, in DataLogger
    temp_distance = np.round(logger.collect_data("SensorData", getData, temp_distance, tsamp=5, nsamp=5),2) #make sure tsamp > 5 seconds or distance sensor will freak
  File "/home/pi/AutoAquaponics/data.py", line 94, in collect_data
    getdata = dataget(temp_distance)
  File "/home/pi/AutoAquaponics/getData.py", line 21, in getData
    wtemp = wt_sensor.get_temperature()
  File "/usr/local/lib/python3.7/dist-packages/w1thermsensor/core.py", line 328, in get_temperature
    value = self.raw_sensor_count
  File "/usr/local/lib/python3.7/dist-packages/w1thermsensor/core.py", line 264, in raw_sensor_count
    bytes = self.raw_sensor_strings[1].split()
  File "/usr/local/lib/python3.7/dist-packages/w1thermsensor/core.py", line 243, in raw_sensor_strings
    if data[0].strip()[-3:] != "YES":
IndexError: list index out of range
`

Not sure if this is going to be a recurring issue or not, but there seems to be something wrong with the actual temperature sensor library (not our code), which crashed getData.py. This might be a hardware issue instead of software too, but that's TBD. Made this issue just so we have some record of this happening in case this error becomes a problem in the future.

**Comment by billyen33** [comment]
It happened again, and there's a GitHub issue [here](https://github.com/timofurrer/w1thermsensor/issues/94) that seems to describe something similar to what we are facing. Need to resolve this somehow so our software program doesn't crash regularly.

**Comment by billyen33** [comment]
After the fix, the new error became:
`Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 48, in start_data_logging
    DataLogger()
  File "/home/pi/AutoAquaponics/DataLogger.py", line 25, in DataLogger
    temp_distance = np.round(logger.collect_data("SensorData", getData, temp_distance, tsamp=5, nsamp=5),2) #make sure tsamp > 5 seconds or distance sensor will freak
  File "/home/pi/AutoAquaponics/data.py", line 94, in collect_data
    getdata = dataget(temp_distance)
  File "/home/pi/AutoAquaponics/getData.py", line 21, in getData
    wtemp = wt_sensor.get_temperature()
  File "/usr/local/lib/python3.7/dist-packages/w1thermsensor/core.py", line 332, in get_temperature
    value = self.raw_sensor_count
  File "/usr/local/lib/python3.7/dist-packages/w1thermsensor/core.py", line 268, in raw_sensor_count
    bytes = self.raw_sensor_strings[1].split()
  File "/usr/local/lib/python3.7/dist-packages/w1thermsensor/core.py", line 248, in raw_sensor_strings
    raise SensorNotReadyError(self)
w1thermsensor.errors.SensorNotReadyError: Sensor 041636098eff is not yet ready to read temperature
`
data was most likely empty for unknown reasons, which crashed our code. Maybe this is a hardware problem, because the sensor we have was very old and the connection to that terminal block might not be great. This is a big problem though because it crashes our code after running main.py for ~24 hours, and we will need to address this before deploying our water monitoring system.
